In [8]:
from PIL import Image
import numpy as np
import os
from os import listdir
from os.path import isfile, join

def parseImFilename(imFilename, imPath):
    
    #Open the Image given by imFilename and Path @ imPath
    
    im = Image.open(os.path.join(imPath, imFilename))  
    
    #Get the Height and width for the image.
    width, height = im.size
    
    #new_File = open("D:/WiderFace/output/" + os.path.splitext(imFilename)[0] +".txt","w+")
     
    #Open the WiderFace split
    with open("D:/WiderFace/wider_face_split/wider_face_split/wider_face_train_bbx_gt.txt") as myFile:
        for num, line in enumerate(myFile, 1):
                if imFilename in line:
                    
                    myNumber = myFile.readline()
                    #print ('Number_of_classes', myNumber)
                    np.set_printoptions(precision=6)
                    for i in range (int(myNumber)):
                        temp = np.array(myFile.readline().split()).astype(np.float)
                        dx = round((temp[0]+(temp[2]/2))/width,6)
                        dy = round((temp[1]+(temp[3]/2))/height,6)
                        dw = round(temp[2]/width,6)
                        dh = round(temp[3]/height,6)
                        new_File_line = "0 %s %s %s %s\n" % (dx,dy,dw,dh)
                        print(new_File_line)
                        #new_File.write(new_File_line)
                    
                    #new_File.close()
    return imFilename, str(width), str(height)

def listDiectory(imPath):
    
    onlyfiles = [f for f in listdir(imPath) if isfile(join(imPath, f))]
    for i in range (len(onlyfiles)):
        print(onlyfiles[i])
        parseImFilename(onlyfiles[i], imPath)
        
def printDirectory(imPath):
    onlyfiles = [f for f in listdir(imPath) if isfile(join(imPath, f))]
    for i in range (len(onlyfiles)):
        print("/home/liuyan/Desktop/darknet/data/sample_train/output/" + onlyfiles[i])
        


    


In [178]:
print(parseImFilename("0_Parade_marchingband_1_5.jpg","D:/WiderFace/WIDER_train/WIDER_train/images/0--Parade"))

found at line: 4972
Number_of_classes 10

0 0.501465 0.296486 0.036133 0.074671

0 0.415039 0.332357 0.037109 0.070278

0 0.327148 0.342606 0.037109 0.061493

0 0.234375 0.36164 0.037109 0.061493

0 0.038086 0.330161 0.03125 0.051245

0 0.91748 0.274524 0.040039 0.062958

0 0.78418 0.25549 0.037109 0.065886

0 0.716309 0.311127 0.038086 0.065886

0 0.595703 0.297218 0.03125 0.052709

0 0.158691 0.338946 0.032227 0.048316

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
('0_Parade_marchingband_1_5.jpg', '1024', '683')


In [9]:
print(listDiectory( "D:/WiderFace/WIDER_train/WIDER_train/images/0--Parade"))

0_Parade_marchingband_1_100.jpg
0 0.439453 0.307918 0.033203 0.061584

0 0.111816 0.344575 0.051758 0.093842

0 0.02002 0.321848 0.030273 0.048387

0 0.311035 0.293255 0.043945 0.076246

0 0.230957 0.277126 0.03418 0.067449

0 0.918457 0.47654 0.079102 0.14956

0 0.773926 0.302786 0.024414 0.05132

0 0.582031 0.269062 0.039062 0.065982

0 0.533203 0.293255 0.033203 0.058651

0_Parade_marchingband_1_1015.jpg
0 0.356445 0.301611 0.162109 0.333821

0_Parade_marchingband_1_1018.jpg
0 0.141113 0.316912 0.06543 0.113235

0 0.403809 0.458088 0.041992 0.086765

0 0.664551 0.472059 0.02832 0.058824

0 0.923828 0.530882 0.019531 0.041176

0 0.833496 0.481618 0.026367 0.048529

0_Parade_marchingband_1_1022.jpg
0 0.026855 0.641467 0.004883 0.013473

0 0.022461 0.556138 0.021484 0.043413

0 0.047363 0.629491 0.008789 0.019461

0 0.083008 0.636228 0.011719 0.020958

0 0.115723 0.638473 0.010742 0.022455

0 0.141113 0.66018 0.004883 0.008982

0 0.160156 0.665419 0.005859 0.010479

0 0.17041 0.658683 

In [5]:
print(printDirectory( "D:/WiderFace/WIDER_train/WIDER_train/images/0--Parade"))


/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_100.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1015.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1018.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1022.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1030.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1031.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1038.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1046.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1047.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_1048.jpg
/home/liuyan/Desktop/darknet/data/sample_train/output/0_Parade_marchingband_1_108.jpg
/home/liuyan/Desktop/darknet/data/sample_trai